name: sigsample
channels:
  - conda-forge
dependencies:
  - python>=3.7.7,<=3.9
  - pip>=19.1
  - pip:
    - h5py=2.10.0
    - hdf5=1.10.6
    - numpy>=1.21.6
    - scipy>=1.6.2 
    - fdsa @ git+https://github.com/PaccMann/fdsa
    - torch>=1.9.0
    - brc-pytorch >= 0.1.3
    - interpret==0.4.1
    - interpret_core==0.4.1
    # data analysis
    - pandas>=1.3.3
    - scikit-learn==0.24.2
    - matplotlib>=3.2.2
    - seaborn>=0.11.2
    - scikit-image==0.16.2
    - umap-learn=0.5.2
    - imblearn == 0.10.0
    # dev tools
    - pytest==5.4.2
    - flake8=3.8.2
    - yaml=0.2.5
    - yapf=0.28.0
    - black==22.10.0
